# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
    allow_credentials: false
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
      max_age: 3600