framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Serializer\CustomSerializer'
                options:
                    queues:
                        security:
                            binding_keys: ['security']

        routing:
            'App\Message\SecurityMessage': async
