/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/Base/AppDrawer.vue')['default']
    AppHeader: typeof import('./src/components/Base/AppHeader.vue')['default']
    BrandSummary: typeof import('./src/components/Dashboard/BrandSummary.vue')['default']
    MentionsTable: typeof import('./src/components/Dashboard/MentionsTable.vue')['default']
    MentionsTrendsChart: typeof import('./src/components/Dashboard/MentionsTrendsChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentimentOverview: typeof import('./src/components/Dashboard/SentimentOverview.vue')['default']
    SourceDistribution: typeof import('./src/components/Dashboard/SourceDistribution.vue')['default']
  }
}
