server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "http://localhost:5601"
monitoring.ui.container.elasticsearch.enabled: true # Для корректного сбора метрик с elastic search, запущенного в контейнере

elasticsearch.hosts: [ "http://es:9200" ]
elasticsearch.username: kibana_system
elasticsearch.password: WfdaD+OjiHe4X4nRgwY0