cluster.name: "elk"
network.host: 0.0.0.0 # Для корректной работы внутри контейнера
transport.host: 127.0.0.1
http.host: 0.0.0.0

xpack.security.enabled: true # Для поддержки функционала, обеспечивающего безопасность кластера
xpack.license.self_generated.type: basic